development:
  adapter: postgresql
  database: cfchat_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cfchat_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cfchat_production
  host: localhost
  pool: 5
  timeout: 5000
